### ISSUE TITLE
Error !

### ISSUE THREAD

**Issue by SeekPoint** [y0ast/VAE-Torch#10]
envy@ub1404:~/os_pri/github/VAE-Torch$ th main.lua
 [======================================== 499/499 ====================================>]  Tot: 1m8s | Step: 135ms  
Epoch: 1 Lowerbound: 165.41410384644 time: 68.586935043335  
 [======================================== 499/499 ====================================>]  Tot: 1m13s | Step: 174ms  
Epoch: 2 Lowerbound: 122.62024767955 time: 73.759642124176  
/home/envy/torch/install/bin/luajit: cannot open <save/parameters.t7> in mode  w at /tmp/luarocks_torch-scm-1-8096/torch7/lib/TH/THDiskFile.c:640
stack traceback:
    [C]: at 0x7f1619f91110
    [C]: in function 'DiskFile'
    /home/envy/torch/install/share/lua/5.1/torch/File.lua:385: in function 'save'
    main.lua:130: in main chunk
    [C]: in function 'dofile'
    ...envy/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406260
envy@ub1404:~/os_pri/github/VAE-Torch

**Comment by y0ast** [comment]
Could you create a folder called "save" inside the VAE-Torch folder? I think that should solve it.

**Comment by SeekPoint** [comment]
yes, it works
