### ISSUE TITLE
Does this project include image generation code?

### ISSUE THREAD

**Issue by sunshineatnoon** [y0ast/VAE-Torch#12]
Thanks for this project, it clearly shows how to implement VAE in torch.

I ran 'main.lua' to train a model, then I tried `python plot.py`, but I got following error:

```
IOError: Unable to open file (Unable to open file: name = 'params/ff_epoch_740.hdf5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
```

Is plot.py the file that generate image? If so, how can I run this file? Thanks!

**Comment by y0ast** [comment]
Hey! The plotting code is outdated so I removed it, you can still use it as inspiration for how to make a manifold, but I won't update it :)
