### ISSUE TITLE
how much time it takes....

### ISSUE THREAD

**Issue by SeekPoint** [y0ast/VAE-Torch#14]
not done yet  after 10 days on a intel i5820

**Comment by xcyan** [comment]
You need to have gpus.

**Comment by SeekPoint** [comment]
I got  two gtx1080 , but there isn't an option to run on GPU...

**Comment by y0ast** [comment]
Even on a CPU the experiments from the paper should not be more than a few hours to 1 day. What dataset are you training on? Is lower bound improving?

**Comment by SeekPoint** [comment]
[======================================== 499/499 ====================================>]  Tot: 4m55s | Step: 587ms
Epoch: 2040 Lowerbound: 98.350686907702 time: 295.93010878563
 [======================================== 499/499 ====================================>]  Tot: 4m13s | Step: 427ms
Epoch: 2041 Lowerbound: 98.379177907564 time: 253.59385895729
 [======================================== 499/499 ====================================>]  Tot: 2m35s | Step: 222ms
Epoch: 2042 Lowerbound: 98.353038132161 time: 155.83764314651
 [======================================== 499/499 ====================================>]  Tot: 1m47s | Step: 219ms

I just run th main.lua

:~/prj/VAE-Torch$ tree
.
├── datasets
│   ├── freyfaces.hdf5
│   └── mnist.hdf5
├── GaussianCriterion.lua
├── KLDCriterion.lua
├── LICENSE
├── load.lua
├── main.lua
├── plot.py
├── README.md
├── Sampler.lua
├── save
│   ├── lowerbound.t7
│   ├── parameters.t7
│   └── state.t7
├── VAE.lua
├── yknote_log---not_done
└── yknote_log---several_days_not_done

2 directories, 16 files
rzai@rzai00:~/prj/VAE-Torch$

**Comment by y0ast** [comment]
So... that's exactly the score Kingma gets in the paper: https://arxiv.org/pdf/1312.6114v10.pdf

You are finished. The program is not set to terminate at a certain threshold.
