### ISSUE TITLE
NLL number after change of dataset?

### ISSUE THREAD

**Issue by hyqneuron** [y0ast/VAE-Torch#17]
Hi Joost,

I noticed you recently changed the MNIST dataset to a new version. What are the differences?

Thanks,
Yunqing

**Comment by hyqneuron** [comment]
Also, have you tried using the mnist dataset from `require 'mnist'`? I realize when I use that dataset the NLL drops to below 80. Not sure what the differences are, though.

**Comment by y0ast** [comment]
The biggest reason for the change is that I wanted to get rid of the hdf5 library.

The binarized mnist has actual 0 and 1 values, instead of close 0 and close to 1. In practice, papers usually report scores on both these days.

Where did you get that mnist package from? I don't see it.

**Comment by hyqneuron** [comment]
Hmm, seems the `require 'mnist'` I was using was a non-standard source from https://github.com/andresy/mnist

Anw, looks like your data source is legit. Thanks for answering!
