### ISSUE TITLE
Inputs to KLD criterion are mean and variance?

### ISSUE THREAD

**Issue by cjmcmurtrie** [y0ast/VAE-Torch#8]
I have a question I haven't been able to clear up anywhere else.

The only inputs to the KLD criterion are the mean and variance vectors, the outputs of `log_var` after the encoder. These are just outputs of two linear layers. They are the mean and variance of the prior p(Z).

Isn't the KL divergence term supposed to measure the divergence between p(Z) and q(Z|X)? How is this estimated by only having the definition of the prior, i.e. the mean and variance of p(Z)?

The lines of code that I'm talking about are:

From main.lua:

```
local mean, log_var = encoder(input):split(2)
local z = nn.Sampler()({mean, log_var})
...
local KLDerr = KLD:forward(mean, log_var)
```

Above, KLD only looks at `mean` and `log_var`. These are both summary statistics of the prior, and are both outputs of the linear layers proceeding the encoder's output. What is the interpretation where KLD also considers the posterior q(Z|X)?

**Comment by OttoFabius** [comment]
In this implementation, the prior p(z) has mean 0 and variance 1. The mean and log_var you refer to are the encoding of the posterior distribution q(z|x). KLD:forward calculates the kl divergence between q(z|x) and p(z). Let me know if this clears things up.

**Comment by cjmcmurtrie** [comment]
This makes perfect sense, now that I think about it - thank you very much! And complements for this extremely clear, efficient and fast implementation - it makes Var-AE simple with hardly any documenting comments :)
