### ISSUE TITLE
lower bond?

### ISSUE THREAD

**Issue by ghost** [y0ast/VAE-Torch#9]
Thanks for the code. I am just confused about the variable batchlowerbound in main.lua.
Why batchlowerbound = reconstruc_err + KLDerr, instead of -KLDerr + E_q[p(x|z)] ? 
This seems to be the error induced when maximising the lower bond?

**Comment by y0ast** [comment]
This version of the VAE optimizes the negative log-likelihood, which is why the sign on the batchlowerbound is flipped from what you expected.
